### ISSUE TITLE
Fix vertical align issue

### ISSUE THREAD

**Issue by dongheeleeme** [Mark2Mark/gintronic#8] opened 2021-05-12 07:54 UTC
Hi, Thanks for the great font 😄 
I could see the vertical-aligning issue in the `Kitty` terminal and `Sublime Text`. I think It works very well in other IDE and Terminal. Could you please have a look at this issue? Also, Could you please support powerline font?

![Screenshot 2021-05-12 at 09 27 31](https://user-images.githubusercontent.com/38916112/117935838-70e18100-b304-11eb-9d75-990a93543217.png)

**Comment by Mark2Mark** [comment] 2021-05-17 15:58
Thank you so much @dongheeleeme! Happy to hear that and happy to help.

I am happy to fix bugs, I need some more info though:

- On which operating system is this?
- May I ask what the exact misalignment is, that you’re pointing to? I see the screenhot, but I am not sure.
- What is powerline font, please?

🙂

**Comment by dongheeleeme** [comment] 2021-05-17 16:07
Hi @Mark2Mark,

Thank you so much for reply 😄 

- I'm using mac os.
- I this Gintronic is top-aligned in some editors like below screenshot.
### Gintronic
<img width="667" alt="Screenshot 2021-05-17 at 18 05 15" src="https://user-images.githubusercontent.com/38916112/118520507-6f67ec80-b73a-11eb-8424-1e3bce31feed.png">

### Other font
<img width="667" alt="Screenshot 2021-05-17 at 18 06 58" src="https://user-images.githubusercontent.com/38916112/118520829-adfda700-b73a-11eb-973b-66e82d54a4ce.png">

- Please ignore powerline font 😄  It's not the related issue.

Thank you!

**Comment by Mark2Mark** [comment] 2021-05-17 16:16
Thank you!

I see, so it’s the text selection box thatthe font seems to hang a little to high in, right?

I’ll see what I can do. It might take a little as I need to do some research, as it seems to be happening only in some editors.

Which file format do you have installed? `otf` or `ttf`?

**Comment by dongheeleeme** [comment] 2021-05-17 16:22
Maybe I installed `ttf` file on my machine.
I really hope this issue is fixed 😄 
Thanks!

**Comment by Mark2Mark** [comment] 2021-05-17 16:37
<img width="583" alt="Screenshot 2021-05-17 at 18 33 47" src="https://user-images.githubusercontent.com/5824595/118524497-83155200-b73e-11eb-9daa-6e2d9b9f019b.png">

It looks like Sublime Text has some parameters in the settings file (there where you also set your font and the font size. Those are `line_padding_top` and `line_padding_bottom`. Depending on your font size, if you fiddle a bit with the numbers, it could work. For me it does.

On a side note: Sublime is a bit peculiar with the font size also. The font size and even the letter spacing jumps more or less between each single font-size. I just updated and it is still the same as it was in 2016 :D

**Comment by dongheeleeme** [comment] 2021-05-17 16:44
Thanks, @Mark2Mark but my screenshot was taken from the kitty terminal 🤔 
Thank you so much for your effort 👍

**Comment by Mark2Mark** [comment] 2021-05-17 16:50
Oh, I could reproduce it in Sublime, so I started with that one.

I don’t have kitty, but does playing around with the custom line spacing in the kitty.conf file help anyhow? Or do they have something similar to the Sublime setting?

**Comment by dongheeleeme** [comment] 2021-05-17 16:52
Let me check it but I think it would be good if this issue is fixed on the font file side 😄 Because I don't want to change settings whenever I use this font.

**Comment by Mark2Mark** [comment] 2021-05-17 16:54
I understand that. But I am trying to debug the issue, because you mentioned that it only happens in Sublime and Kitty. That indicates to me, that the other editors handle the font fine. And I can’t fix if I don’t know yet the reason and/or can reproduce.

**Comment by dongheeleeme** [comment] 2021-05-17 19:02
Yes, It makes sense although a little bit sad 😞 Thank you for supporting my request.

**Comment by Mark2Mark** [comment] 2021-05-17 19:43
Don’t be sad. I am on it, but I need your help to fix that ;) 

As written above

**Comment by dongheeleeme** [comment] 2021-05-18 07:05
Please let me know if you need any help to fix this issue 👍 Thanks!

**Comment by Mark2Mark** [comment] 2021-05-18 07:37
Yes, I’d like to know this:

> I don’t have kitty, but does playing around with the custom line spacing in the kitty.conf file help anyhow? Or do they have something similar to the Sublime setting?

**Comment by dongheeleeme** [comment] 2021-05-18 14:28
> Yes, I’d like to know this:
> 
> > I don’t have kitty, but does playing around with the custom line spacing in the kitty.conf file help anyhow? Or do they have something similar to the Sublime setting?

I couldn't see any options related this one so far 🤔

**Comment by dongheeleeme** [comment] 2021-05-22 10:56
Hi @Mark2Mark 😄 
I found [this one](https://github.com/MonoLisaFont/feedback/issues/5) from another font's issue. Maybe It's the same issue as I wrote here and It seems to be fixed as an updated font version. Please check this link. Thanks!

**Comment by Mark2Mark** [comment] 2021-05-22 12:00
Thank you, I’ll have a look.

Where though, does it say that it was fixed in the font? I only see the sublime people saysing that they fixed that in Sublime.

**Comment by dongheeleeme** [comment] 2021-05-22 14:04
I think this issue is fixed on the font file side as an updated version not sublime only.
![Screenshot 2021-05-22 at 16 03 15](https://user-images.githubusercontent.com/38916112/119229225-399a7d80-bb17-11eb-9c11-27b76b838cdd.png)

**Comment by Tosche** [comment] 2021-05-24 13:08
I had the same report from Donghee regarding my Codelia. I checked how Kitty is highlighting the text, and it's puzzling.
![191189313_174636574581792_1255005537813932235_n](https://user-images.githubusercontent.com/5482424/119349221-cf5c1700-bc95-11eb-818e-e8535d0f4cf3.png)
See the shot 1: How Codelia's vertical metrics are set. typoLineGap is 80, hheaLineGap is 0.
<img width="925" alt="スクリーンショット 2021-05-24 13 32 26" src="https://user-images.githubusercontent.com/5482424/119349337-f87ca780-bc95-11eb-84d6-41195b0c1c8f.png">
Shot 2: From top to bottom: Terminal, Kitty, and Sublime Text.

For Terminal and Sublime, I understand which values are being used. When it comes to Kitty, it's adding something below (a lot more than 80). Kitty's has only one line height/spacing control which adds padding to both top and bottom of the line, so it's not helpful.

Other fonts with the same issue:
Consolas
Droid Sans Mono
Input

Without:
Andale Mono
Belinsky (my past font is fine?????)
Comic Code Ligatures (my past font is fine?????)
Fira Mono
Inconsolata
Iosevka
Menlo
PT Mono
Source Code Pro
Ubuntu Mono

Having compared all these fonts, I do not see what is common among the successful and unsuccessful ones, and precisely what is causing the issue.

**Comment by dongheeleeme** [comment] 2021-05-24 13:23
Thank you so much all. Gintronic and Codelia are my favorite fonts ever so I really need help to fix this issue 🙏

**Comment by Mark2Mark** [comment] 2021-05-25 06:25
Thanks so much for the research @Tosche 
I'll see if I can find some sort of issue.

@dongheeleeme Unfortunately I was too dumb to find an easy way to install kitty. The website is puzzling me to find a download. I am very busy with many projects so I can't spend hours installing random apps that I don't use. Do you have a quick install guide for me?

**Comment by dongheeleeme** [comment] 2021-05-25 07:58
@Mark2Mark Which OS are you using?

**Comment by Mark2Mark** [comment] 2021-05-25 08:14
macOS Big Sur. Thank you!

**Comment by dongheeleeme** [comment] 2021-05-25 08:28
Thanks, I think we can install it using this command on terminal `brew install --cask kitty` 😄 
Ref: https://formulae.brew.sh/cask/kitty

**Comment by dongheeleeme** [comment] 2021-05-26 11:05
@Mark2Mark Was you able to install Kitty on your machine?

**Comment by Tosche** [comment] 2021-05-27 14:49
Upon some hours of investigation, I have come to an observation that the shape of Agrave affects the line height of Kitty for some reason, especially when it exceeds hheaAscender (yes, it affects the bottom bounds). The line spacing is fine when Agrave sits below hheaAscender, but when it's higher, it adds a lot of space at the bottom (the amount doesn't seem to be affected by how much larger the Agrave is). Needless to say the way Kitty handles line height is pretty nonsense and should rely on vertical metrics only. For now, the easy fix for Kitty users is to one of the following options:
- Make only Agrave shorter than hheaAscender.
- Change hheaAscender.
- Serve ASCII-only set (it's for Terminal and Shell scripts and stuff; the users typically do not care for diacritics)

**Comment by Tosche** [comment] 2021-05-27 15:01
I'll file an issue to Kitty first. Let's see how he reacts.

**Comment by Mark2Mark** [comment] 2021-05-27 15:57
Woah, Tosche! Thanks so much for all your time and sweat on this!

**Comment by Tosche** [comment] 2021-05-27 16:00
Shot down after one reply. I've got the same request from another customer of mine before. As he warned me back then, the dev doesn't seem to be a very cooperative type.
https://github.com/kovidgoyal/kitty/issues/3658

**Comment by Tosche** [comment] 2021-05-27 16:02
It's here. Not a very helpful comment and the dev says À is not the issue as far as he is aware, but he does employ a strange method instead of actually looking inside a font.
https://github.com/kovidgoyal/kitty/issues/3658

**Comment by dongheeleeme** [comment] 2021-05-31 08:54
FYI: @Mark2Mark I think @Tosche was fixed this issue. Maybe his way can be helpful for you as well 😄

**Comment by dongheeleeme** [comment] 2021-07-17 09:34
Hi @Mark2Mark, Any updates about this issue?

**Comment by dongheeleeme** [comment] 2022-03-31 08:42
I'll close this issue since it looks not will be solved.

**Comment by Mark2Mark** [comment] 2022-04-01 13:55
Thanks, but I will solve it when I find the time. So I re-opened it again :)

**Comment by dongheeleeme** [comment] 2023-05-07 10:50
I'll close this issue again since it doesn't look will be solved.

**Comment by Mark2Mark** [comment] 2023-05-08 08:35
It’s on my list and will be tackled. Sorry for the waiting.

**Comment by Mark2Mark** [comment] 2023-05-08 09:40
Actually, having a look at the kitti issue that @Tosche opened, I agree that I think the guy fencing the discussion there seems a bit stubborn. Toshi’s observations are right, that they could and should just use the default CoreText line height instead of implementing their own way to calculate it. He blames Apple, but I developed a lot of MacOS apps myself using CoreText and there is nothing wrong with it’s line height. As Toshi also points out in that issue over at kitty, the same fonts behave properly in other apps that use CoreText.

Hence I will close this issue due to a quirky decision of one developer, which I find unreasonable to spend resources on to solve just because they don’t use the CoreText as it is supposed to. Thanks anyway for bringing it to our attention. Maybe Kitty will fix that eventually on their behalf.

**Closed by Mark2Mark** 2023-05-08 09:40 UTC

**Comment by dongheeleeme** [comment] 2024-03-21 08:26
Hi @Mark2Mark, I need your favor. Could you please delete this issue?

**Comment by Mark2Mark** [comment] 2024-03-21 08:31
Hi @dongheeleeme, you mean remove this issue from Github or fix the problem that this issue is about?

**Comment by dongheeleeme** [comment] 2024-03-21 08:40
Hi, I mean removing the issue from the repository. It is not a valid issue anymore.

**Comment by Mark2Mark** [comment] 2024-03-21 09:20
So it works for you now in Kitty?

There is no need to remove an issue from the repository. When it is closed, it is considered removed :)

**Comment by dongheeleeme** [comment] 2024-10-10 10:24
Hi @Mark2Mark, I thought this issue is not related to font itself. It's different by terminals. I thought that it's better to delete this issue in order to do not make any confusion for others.

**Comment by Mark2Mark** [comment] 2024-10-10 10:32
Thanks @dongheeleeme, that's a valid point. However in GitHub it's not possible to really delete an issue (afaik). One can only close it. It will still be visible under the "closed issues". But that's okay, I guess.

Hope you can still work with the font? Does it work for you now?

**Comment by dongheeleeme** [comment] 2024-10-10 10:34
Thanks for your quick response, If you have admin permission, I think you can delete an issue.
https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/deleting-an-issue

**Comment by Mark2Mark** [comment] 2024-10-10 16:05
Ah thanks so much. Didn't know that, last time I checked it wasn't available. I think I'll still keep the issue as a reference. There are good Information collected here. Thanks for your time!
